homebrew_installed_packages:
  - autoconf
  - fzf
  - tree
  - task
  - timewarrior
  - stow
  - autoconf
  - bash-completion
  - doxygen
  - gettext
  - gifsicle
  - git
  - httpie
  - go
  - gpg
  - hub
  - httpie
  - libevent
  - sqlite
  - mcrypt
  - nmap
  - node
  - nvm
  - ssh-copy-id
  - readline
  - openssl
  - pv
  - wget
  - wrk
  - htop
  - mc
  - zsh 
  - tmux
  - jq
  - bzr

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - firefox
    #TODO install this theme https://raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/master/schemes/FrontEndDelight.itermcolors
  - iterm2
  - google-chrome
  - slack
  - spectacle
  - vlc 
  - 1password 
  - java
  - visual-studio-code
  - google-backup-and-sync
