homebrew_installed_packages:
  - autoconf
  - fzf
  - kubernetes-cli
  - kustomize
  - tree
  - task
  - timewarrior
  - stow
  - autoconf
  - bash-completion
  - doxygen
  - gettext
  - gifsicle
  - git
  - go
  - gpg
  - hub
  - httpie
  - iperf
  - libevent
  - sqlite
  - mcrypt
  - nmap
  - node
  - nvm
  - ssh-copy-id
  - readline
  - openssl
  - pv
  - wget
  - wrk
  - htop
  - mc
  - zsh 
  - tmux
  - jq
  - bzr
  - neovim

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - anki
  - chromedriver
  - dash
  - docker
  - firefox
//TODO install this theme https://raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/master/schemes/FrontEndDelight.itermcolors
  - iterm2
  - google-chrome
  - handbrake
  - licecap
  - sequel-pro
  - skitch
  - slack
  - spectacle
  - transmit
  - vagrant
  - vlc 
  - spotify
  - 1password 
  - java
  - visual-studio-code

