homebrew_installed_packages:
  - autoconf
  - reattach-to-user-namespace
  - raycast 
  - fzf
  - tree
  - stow
  - autoconf
  - bash-completion
  - doxygen
  - gettext
  - gifsicle
  - git
  - httpie
  - gpg
  - grpcurl
  - hub
  - httpie
  - libevent
  - sqlite
  - mcrypt
  - nmap
  - node
  - nvm
  - ssh-copy-id
  - readline
  - openssl
  - pv
  - wget
  - wrk
  - htop
  - mc
  - zsh 
  - tmux
  - jq
  - yq
  - bzr
  - java
  - direnv
  # python related 
  - pyenv
  - pyenv-virtualenv
  - python3

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - firefox
  - iterm2
  - brave-browser
  - slack
  - vlc 
  - 1password 
  - visual-studio-code
  - google-drive
  - font-fira-code
  - zoom
  - pop
  - 1password-cli
  - docker
